export const REQUEST_WEATHER_DATA = 'REQUEST_WEATHER_DATA';
export const SUCCESS_WEATHER_DATA = 'SUCCESS_WEATHER_DATA';
export const FAILED_WEATHER_DATA = 'FAILED_WEATHER_DATA';
export const STORE_STATE = 'STORE_STATE';
export const TOGGLE_TEMP = 'TOGGLE_TEMP';
export const REQUEST_CURRENT_LOCATION = 'REQUEST_CURRENT_LOCATION';
export const CURRENT_CITY_DATA = 'CURRENT_CITY_DATA';
